export const BOOK_SECTIONS = ["reading", "read"] as const;

export type BookSection = (typeof BOOK_SECTIONS)[number];

export type Book = {
  id: string;
  title: string;
  author: string;
  coverSrc: string;
  href: string;
  section: BookSection;
  rating?: number;
};

export const BOOKS = [
  {
    id: "the-creative-act",
    title: "The Creative Act",
    author: "Rick Rubin",
    coverSrc: "/books/the-creative-act.png",
    href: "https://oku.club/book/the-creative-act-by-rick-rubin-nZ8Dw",
    section: "reading",
  },
  {
    id: "great-thinkers",
    title: "Great Thinkers",
    author: "The School of Life",
    coverSrc: "/books/great-thinkers.jpg",
    href: "https://oku.club/book/great-thinkers-by-the-school-of-life-KuFDe",
    section: "reading",
  },
  {
    id: "design-is-storytelling",
    title: "Design Is Storytelling",
    author: "Ellen Lupton",
    coverSrc: "/books/design-is-storytelling.jpg",
    href: "https://oku.club/book/design-is-storytelling-by-ellen-lupton-f2nT2",
    section: "reading",
  },
  {
    id: "how-to-live",
    title: "How to Live",
    author: "Derek Sivers",
    coverSrc: "/books/how-to-live.jpeg",
    href: "https://oku.club/book/how-to-live-by-derek-sivers-91nzy",
    section: "read",
    rating: 4,
  },
  {
    id: "good-charts",
    title: "Good Charts",
    author: "Scott Berinato",
    coverSrc: "/books/good-charts.jpg",
    href: "https://oku.club/book/good-charts-by-scott-berinato-2kpss",
    section: "read",
    rating: 3.5,
  },
  {
    id: "the-vegetarian",
    title: "The Vegetarian",
    author: "Han Kang",
    coverSrc: "/books/the-vegetarian.jpg",
    href: "https://oku.club/book/the-vegetarian-by-han-kang-njFul",
    section: "read",
    rating: 4.5,
  },
  {
    id: "anxious-people",
    title: "Anxious People",
    author: "Fredrik Backman",
    coverSrc: "/books/anxious-people.jpg",
    href: "https://oku.club/book/anxious-people-by-fredrik-backman-oc1ec",
    section: "read",
    rating: 4.5,
  },
  {
    id: "homo-deus",
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    coverSrc: "/books/homo-deus.jpg",
    href: "https://oku.club/book/homo-deus-by-yuval-noah-harari-QRtIP",
    section: "read",
    rating: 4,
  },
  {
    id: "the-complete-maus",
    title: "The Complete Maus",
    author: "Art Spiegelman",
    coverSrc: "/books/the-complete-maus.jpg",
    href: "https://oku.club/book/the-complete-maus-by-art-spiegelman-RtdBW",
    section: "read",
    rating: 5,
  },
  {
    id: "convenience-store-woman",
    title: "Convenience Store Woman",
    author: "Sayaka Murata",
    coverSrc: "/books/convenience-store-woman.jpg",
    href: "https://oku.club/book/convenience-store-woman-by-sayaka-murata-qlZrJ",
    section: "read",
    rating: 4,
  },
  {
    id: "the-little-coffee-shop-of-kabul",
    title: "The Little Coffee Shop of Kabul",
    author: "Deborah Rodriguez",
    coverSrc: "/books/the-little-coffee-shop-of-kabul.jpg",
    href: "https://oku.club/book/the-little-coffee-shop-of-kabul-by-deborah-rodriguez-3sq8c",
    section: "read",
    rating: 4,
  },
  {
    id: "klara-and-the-sun",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    coverSrc: "/books/klara-and-the-sun.jpg",
    href: "https://oku.club/book/klara-and-the-sun-by-kazuo-ishiguro-K66uu",
    section: "read",
    rating: 5,
  },
  {
    id: "this-is-your-mind-on-plants",
    title: "This Is Your Mind on Plants",
    author: "Michael Pollan",
    coverSrc: "/books/this-is-your-mind-on-plants.jpg",
    href: "https://oku.club/book/this-is-your-mind-on-plants-by-michael-pollan-RPBMe",
    section: "read",
    rating: 4,
  },
  {
    id: "lie-with-me",
    title: "Lie With Me",
    author: "Philippe Besson",
    coverSrc: "/books/lie-with-me.jpg",
    href: "https://oku.club/book/lie-with-me-by-philippe-besson-ppHWz",
    section: "read",
    rating: 3.5,
  },
  {
    id: "keep-going",
    title: "Keep Going",
    author: "Austin Kleon",
    coverSrc: "/books/keep-going.jpg",
    href: "https://oku.club/book/keep-going-by-austin-kleon-gH4pb",
    section: "read",
    rating: 3.5,
  },
  {
    id: "show-your-work",
    title: "Show Your Work!",
    author: "Austin Kleon",
    coverSrc: "/books/show-your-work.jpg",
    href: "https://oku.club/book/show-your-work-by-austin-kleon-tHHXG",
    section: "read",
    rating: 3.5,
  },
  {
    id: "before-your-memory-fades",
    title: "Before Your Memory Fades",
    author: "Toshikazu Kawaguchi",
    coverSrc: "/books/before-your-memory-fades.jpg",
    href: "https://oku.club/book/before-your-memory-fades-by-toshikazu-kawaguchi-icLKH",
    section: "read",
    rating: 3.5,
  },
  {
    id: "panenka",
    title: "PANENKA.",
    author: "RONAN. HESSION",
    coverSrc: "/books/panenka.jpg",
    href: "https://oku.club/book/panenka-by-ronan-hession-59np3",
    section: "read",
    rating: 4,
  },
  {
    id: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    coverSrc: "/books/project-hail-mary.jpg",
    href: "https://oku.club/book/project-hail-mary-by-andy-weir-l5lKi",
    section: "read",
    rating: 5,
  },
  {
    id: "a-man-called-ove",
    title: "A Man Called Ove",
    author: "Fredrik Backman",
    coverSrc: "/books/a-man-called-ove.jpg",
    href: "https://oku.club/book/a-man-called-ove-by-fredrik-backman-xRIlm",
    section: "read",
    rating: 4.5,
  },
  {
    id: "creative-selection",
    title: "Creative Selection",
    author: "Ken Kocienda",
    coverSrc: "/books/creative-selection.jpg",
    href: "https://oku.club/book/creative-selection-by-ken-kocienda-SRgMV",
    section: "read",
    rating: 4.5,
  },
  {
    id: "tales-from-the-cafe",
    title: "Tales from the Cafe",
    author: "Sunmark Publishing, Inc., Toshikazu Kawaguchi",
    coverSrc: "/books/tales-from-the-cafe.jpg",
    href: "https://oku.club/book/tales-from-the-cafe-by-sunmark-publishing-inc-ShMuX",
    section: "read",
    rating: 4,
  },
  {
    id: "how-to-survive-the-modern-world",
    title: "How to Survive the Modern World",
    author: "The School of Life",
    coverSrc: "/books/how-to-survive-the-modern-world.jpg",
    href: "https://oku.club/book/how-to-survive-the-modern-world-by-the-school-of-life-8tw1y",
    section: "read",
    rating: 4.5,
  },
  {
    id: "the-housekeeper-and-the-professor",
    title: "The Housekeeper and the Professor",
    author: "Yōko Ogawa",
    coverSrc: "/books/the-housekeeper-and-the-professor.jpg",
    href: "https://oku.club/book/the-housekeeper-and-the-professor-by-y%C5%8Dko-ogawa-AQR4i",
    section: "read",
    rating: 4.5,
  },
  {
    id: "the-stranger",
    title: "The Stranger",
    author: "Albert Camus",
    coverSrc: "/books/the-stranger.jpg",
    href: "https://oku.club/book/the-stranger-by-albert-camus-ohwtf",
    section: "read",
    rating: 4.5,
  },
  {
    id: "the-vanishing-half",
    title: "The Vanishing Half",
    author: "Brit Bennett",
    coverSrc: "/books/the-vanishing-half.jpg",
    href: "https://oku.club/book/the-vanishing-half-by-brit-bennett-Nbgod",
    section: "read",
    rating: 4,
  },
  {
    id: "how-to-travel",
    title: "How to Travel",
    author: "The School of Life",
    coverSrc: "/books/how-to-travel.jpg",
    href: "https://oku.club/book/how-to-travel-by-the-school-of-life-2JOCj",
    section: "read",
    rating: 4,
  },
  {
    id: "piranesi",
    title: "Piranesi",
    author: "Susanna Clarke",
    coverSrc: "/books/piranesi.jpg",
    href: "https://oku.club/book/piranesi-by-susanna-clarke-9slqI",
    section: "read",
    rating: 5,
  },
  {
    id: "into-the-wild",
    title: "Into the Wild",
    author: "Jon Krakauer",
    coverSrc: "/books/into-the-wild.jpg",
    href: "https://oku.club/book/into-the-wild-by-jon-krakauer-XBvDW",
    section: "read",
    rating: 3.5,
  },
  {
    id: "norwegian-wood",
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    coverSrc: "/books/norwegian-wood.jpg",
    href: "https://oku.club/book/norwegian-wood-by-haruki-murakami-Qm8xO",
    section: "read",
    rating: 4.5,
  },
  {
    id: "kenya-hara-designing-japan",
    title: "Kenya Hara: Designing Japan",
    author: "Kenya Hara",
    coverSrc: "/books/kenya-hara-designing-japan.jpg",
    href: "https://oku.club/book/kenya-hara-by-kenya-hara-42T0T",
    section: "read",
    rating: 3.5,
  },
  {
    id: "a-short-history-of-nearly-everything",
    title: "A Short History of Nearly Everything",
    author: "Bill Bryson",
    coverSrc: "/books/a-short-history-of-nearly-everything.jpg",
    href: "https://oku.club/book/a-short-history-of-nearly-everything-by-bill-bryson-h2BuR",
    section: "read",
    rating: 3.5,
  },
  {
    id: "harry-potter-ravenclaw",
    title: "Harry Potter and the Philosopher's Stone - Ravenclaw Edition",
    author: "Joanne K. Rowling",
    coverSrc: "/books/harry-potter-ravenclaw.jpg",
    href: "https://oku.club/book/harry-potter-and-the-philosophers-sto...-by-joanne-k-rowling-ngP8D",
    section: "read",
    rating: 4.5,
  },
  {
    id: "before-the-coffee-gets-cold",
    title: "Before the Coffee Gets Cold",
    author: "Toshikazu Kawaguchi",
    coverSrc: "/books/before-the-coffee-gets-cold.jpg",
    href: "https://oku.club/book/before-the-coffee-gets-cold-by-toshikazu-kawaguchi-VQUBo",
    section: "read",
    rating: 4.5,
  },
  {
    id: "in-watermelon-sugar",
    title: "In Watermelon Sugar",
    author: "Richard Brautigan",
    coverSrc: "/books/in-watermelon-sugar.jpg",
    href: "https://oku.club/book/in-watermelon-sugar-by-richard-brautigan-OLsQT",
    section: "read",
    rating: 3.5,
  },
  {
    id: "kari",
    title: "Kari",
    author: "Amruta Patil",
    coverSrc: "/books/kari.jpg",
    href: "https://oku.club/book/kari-by-amruta-patil-eXvmK",
    section: "read",
    rating: 3.5,
  },
  {
    id: "fahrenheit-451",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    coverSrc: "/books/fahrenheit-451.jpg",
    href: "https://oku.club/book/fahrenheit-451-by-ray-bradbury-3m0eE",
    section: "read",
    rating: 4,
  },
  {
    id: "the-diary-of-a-young-girl",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    coverSrc: "/books/the-diary-of-a-young-girl.jpg",
    href: "https://oku.club/book/the-diary-of-a-young-girl-by-anne-frank-yc7Br",
    section: "read",
    rating: 5,
  },
  {
    id: "siddhartha",
    title: "Siddhartha",
    author: "Hermann Hesse",
    coverSrc: "/books/siddhartha.jpg",
    href: "https://oku.club/book/siddhartha-by-hermann-hesse-cCdzG",
    section: "read",
    rating: 4.5,
  },
  {
    id: "evolv",
    title: "EVOLV",
    author: "Ryan Sequeira",
    coverSrc: "/books/evolv.jpg",
    href: "https://oku.club/book/evolv-by-ryan-sequeira-iEEDz",
    section: "read",
    rating: 4,
  },
  {
    id: "mans-search-for-meaning",
    title: "Man's Search For Meaning",
    author: "Viktor E Frankl",
    coverSrc: "/books/mans-search-for-meaning.jpg",
    href: "https://oku.club/book/mans-search-for-meaning-by-viktor-e-frankl-LHJhk",
    section: "read",
    rating: 4.5,
  },
  {
    id: "the-alchemist-25th-anniversary",
    title: "The Alchemist 25th Anniversary",
    author: "Paulo Coelho",
    coverSrc: "/books/the-alchemist-25th-anniversary.jpg",
    href: "https://oku.club/book/the-alchemist-25th-anniversary-by-paulo-coelho-QbHjS",
    section: "read",
    rating: 4,
  },
  {
    id: "beyond-religion",
    title: "Beyond Religion",
    author: "The Dalai Lama",
    coverSrc: "/books/beyond-religion.jpg",
    href: "https://oku.club/book/beyond-religion-by-the-dalai-lama-LDkzk",
    section: "read",
    rating: 3.5,
  },
  {
    id: "the-mom-test",
    title: "The Mom Test",
    author: "Rob Fitzpatrick",
    coverSrc: "/books/the-mom-test.jpg",
    href: "https://oku.club/book/the-mom-test-by-rob-fitzpatrick-vceQr",
    section: "read",
    rating: 3.5,
  },
  {
    id: "never-split-the-difference",
    title: "Never Split the Difference",
    author: "Chris Voss",
    coverSrc: "/books/never-split-the-difference.jpg",
    href: "https://oku.club/book/never-split-the-difference-by-chris-voss-vY6rA",
    section: "read",
    rating: 3.5,
  },
  {
    id: "thinking-with-type",
    title: "Thinking with Type",
    author: "Ellen Lupton",
    coverSrc: "/books/thinking-with-type.jpg",
    href: "https://oku.club/book/thinking-with-type-by-ellen-lupton-kMpYW",
    section: "read",
    rating: 4.5,
  },
  {
    id: "be-here-now",
    title: "Be Here Now",
    author: "Ram Dass",
    coverSrc: "/books/be-here-now.jpg",
    href: "https://oku.club/book/be-here-now-by-ram-dass-6P6dS",
    section: "read",
    rating: 4,
  },
  {
    id: "land-of-seven-rivers",
    title: "Land of seven rivers",
    author: "Sanjeev Sanyal",
    coverSrc: "/books/land-of-seven-rivers.jpg",
    href: "https://oku.club/book/land-of-seven-rivers-by-sanjeev-sanyal-fQ0oH",
    section: "read",
    rating: 4,
  },
  {
    id: "why-we-sleep",
    title: "Why We Sleep",
    author: "Matthew Walker",
    coverSrc: "/books/why-we-sleep.jpg",
    href: "https://oku.club/book/why-we-sleep-by-matthew-walker-e03Ys",
    section: "read",
    rating: 4,
  },
  {
    id: "outgrowing-god",
    title: "Outgrowing God",
    author: "Richard Dawkins",
    coverSrc: "/books/outgrowing-god.jpg",
    href: "https://oku.club/book/outgrowing-god-by-richard-dawkins-KkDEb",
    section: "read",
    rating: 4,
  },
  {
    id: "hooked",
    title: "Hooked",
    author: "Nir Eyal",
    coverSrc: "/books/hooked.jpg",
    href: "https://oku.club/book/hooked-by-nir-eyal-5A6ww",
    section: "read",
    rating: 4,
  },
  {
    id: "rework",
    title: "ReWork",
    author: "Jason Fried",
    coverSrc: "/books/rework.jpg",
    href: "https://oku.club/book/rework-by-jason-fried-h5MxH",
    section: "read",
    rating: 4,
  },
  {
    id: "flow",
    title: "Flow",
    author: "Mihaly Csikszentmihalyi",
    coverSrc: "/books/flow.jpg",
    href: "https://oku.club/book/flow-by-mihaly-csikszentmihalyi-sHm6Z",
    section: "read",
    rating: 4.5,
  },
  {
    id: "make-time",
    title: "Make Time",
    author: "Jake Knapp, John Zeratsky",
    coverSrc: "/books/make-time.jpg",
    href: "https://oku.club/book/make-time-by-jake-knapp-XnZWI",
    section: "read",
    rating: 4,
  },
  {
    id: "the-dip",
    title: "The Dip",
    author: "Seth Godin",
    coverSrc: "/books/the-dip.jpg",
    href: "https://oku.club/book/the-dip-by-seth-godin-VTWDc",
    section: "read",
    rating: 3.5,
  },
  {
    id: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    coverSrc: "/books/atomic-habits.jpg",
    href: "https://oku.club/book/atomic-habits-by-james-clear-I7CgQ",
    section: "read",
    rating: 4,
  },
  {
    id: "pyjama-profit",
    title: "Pyjama Profit",
    author: "Abhinav Chhikara, Varun Mayya",
    coverSrc: "/books/pyjama-profit.jpg",
    href: "https://oku.club/book/pyjama-profit-by-abhinav-chhikara-7tCZA",
    section: "read",
    rating: 3.5,
  },
  {
    id: "rich-dad-poor-dad",
    title: "Rich Dad, Poor Dad",
    author: "Robert T. Kiyosaki, Sharon L. Lechter",
    coverSrc: "/books/rich-dad-poor-dad.jpg",
    href: "https://oku.club/book/rich-dad-poor-dad-by-robert-t-kiyosaki-rewUR",
    section: "read",
    rating: 3,
  },
  {
    id: "sprint",
    title: "Sprint",
    author: "Jake Knapp, John Zeratsky, Braden Kowitz",
    coverSrc: "/books/sprint.jpg",
    href: "https://oku.club/book/sprint-by-jake-knapp-vaP0y",
    section: "read",
    rating: 4,
  },
  {
    id: "living-with-complexity",
    title: "Living with Complexity",
    author: "Donald A. Norman",
    coverSrc: "/books/living-with-complexity.jpg",
    href: "https://oku.club/book/living-with-complexity-by-donald-a-norman-qHkf7",
    section: "read",
    rating: 4,
  },
  {
    id: "the-design-of-everyday-things",
    title: "The Design of Everyday Things",
    author: "Donald A. Norman",
    coverSrc: "/books/the-design-of-everyday-things.jpg",
    href: "https://oku.club/book/the-design-of-everyday-things-by-donald-a-norman-ES3n4",
    section: "read",
    rating: 4,
  },
  {
    id: "steal-like-an-artist",
    title: "Steal Like an Artist",
    author: "Austin Kleon",
    coverSrc: "/books/steal-like-an-artist.jpg",
    href: "https://oku.club/book/steal-like-an-artist-by-austin-kleon-6HpWC",
    section: "read",
    rating: 4.5,
  },
  {
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    coverSrc: "/books/sapiens.jpg",
    href: "https://oku.club/book/sapiens-by-yuval-noah-harari-n0pZB",
    section: "read",
    rating: 5,
  },
] satisfies Book[];
